; platformio.ini
[platformio]
src_dir = .
build_dir = build
default_envs = native

[env]
build_flags =
    -I src
    -I cyan
    -I external/clay
    -I external/lua/lua-5.4.7/src

[env:native]
platform = native
extra_scripts = post:postbuild_native.py
build_src_filter =
    +<src/*>
    +<cyan/*.c>
    +<platform/pc/*>
    +<external/clay/*.c>
    +<external/lua/lua-5.4.7/src/*.c>
    -<external/lua/lua-5.4.7/src/lua.c>
    -<external/lua/lua-5.4.7/src/luac.c>
build_flags =
    ${env.build_flags}
    -DSDL_MAIN_HANDLED
    -I external/SDL3/x86_64-w64-mingw32/include
    -I external/SDL_ttf/x86_64-w64-mingw32/include
    -I external/SDL3_image/x86_64-w64-mingw32/include
    -L external/SDL3/x86_64-w64-mingw32/lib
    -L external/SDL_ttf/x86_64-w64-mingw32/lib
    -L external/SDL3_image/x86_64-w64-mingw32/lib
    -lSDL3
    -lSDL3_ttf
    -lSDL3_image

[env:xiao_esp32s3]
lib_deps = moononournation/GFX Library for Arduino
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_src_filter =
    +<cyan/*.c>
    +<platform/esp32/*>
    +<external/clay/*.c>
    +<external/lua/lua-5.4.7/src/*.c>
    -<src/main.c>
build_flags = ${env.build_flags}