; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
build_dir = build
default_envs = native

[env]
build_flags =
	-I src
	-I cyan
	-I external/clay
	-I external/lua/lua-5.4.7
	-DLUA_C89_NUMBERS

[env:native]
platform = native
extra_scripts = post:postbuild_native.py
build_src_filter =
	+<src/*>
	+<src/tabs/*>
	+<cyan/*.c>
	+<cyan/app_handling/*.c>
	+<cyan/data/*.c>
	+<cyan/tabs/*.c>
	+<platform/pc/*>
	+<external/clay/*.c>
	+<external/lua/lua-5.4.7/*.c>
	-<external/lua/lua-5.4.7/lua.c>
	-<external/lua/lua-5.4.7/luac.c>
	-<external/lua/lua-5.4.7/onelua.c>
build_flags =
	${env.build_flags}
	-DSDL_MAIN_HANDLED
	-I external/SDL3/x86_64-w64-mingw32/include
	-I external/SDL3_image/x86_64-w64-mingw32/include
	-L external/SDL3/x86_64-w64-mingw32/lib
	-L external/SDL3_image/x86_64-w64-mingw32/lib
	-lSDL3
	-lSDL3_image
lib_deps =
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	adafruit/RTClib@^2.1.4

[env:esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c3
framework = arduino
board_build.flash_size = 4MB
lib_deps =
	moononournation/GFX Library for Arduino
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	adafruit/RTClib@^2.1.4
build_src_filter =
	+<src/*>
	+<cyan/*.c>
	+<cyan/tabs/screen_watchface.c>
	+<platform/esp32/*>
	-<platform/esp32/main_cyan.cpp>
	-<src/main.c>
build_flags =
	${env.build_flags}
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32s3zero]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitm-1
framework = arduino
board_build.flash_size = 4MB
board_build.psram_type = qspi
lib_deps =
	moononournation/GFX Library for Arduino
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	adafruit/RTClib@^2.1.4
build_src_filter =
	+<src/*>
	+<cyan/*.c>
	+<cyan/app_handling/*.c>
	+<cyan/data/*.c>
	+<cyan/tabs/*.c>
	+<platform/esp32/*>
	-<platform/esp32/main_watchface.cpp>
	+<external/clay/*.c>
	+<external/lua/lua-5.4.7/*.c>
	-<external/lua/lua-5.4.7/lua.c>
	-<external/lua/lua-5.4.7/luac.c>
	-<external/lua/lua-5.4.7/onelua.c>
	-<src/main.c>
build_flags =
	${env.build_flags}
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM

[env:xiao_esp32s3_plus]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32s3
framework = arduino
board_build.flash_size = 16MB
lib_deps =
	moononournation/GFX Library for Arduino
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	adafruit/RTClib@^2.1.4
build_src_filter =
	+<src/*>
	+<cyan/*.c>
	+<cyan/app_handling/*.c>
	+<cyan/data/*.c>
	+<cyan/tabs/*.c>
	+<platform/esp32/*>
	+<external/clay/*.c>
	+<external/lua/lua-5.4.7/*.c>
	-<external/lua/lua-5.4.7/lua.c>
	-<external/lua/lua-5.4.7/luac.c>
	-<external/lua/lua-5.4.7/onelua.c>
	-<src/main.c>
build_flags =
	${env.build_flags}
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_XIAO_ESP32S3_PLUS